language: r

## minimal travis config
## https://docs.travis-ci.com/user/languages/r/
## https://towardsdatascience.com/travis-ci-for-r-advanced-guide-719cb2d9e0e5

## no tests, coverage
## check as CRAN


script:
  - R CMD build . --compact-vignettes=gs+qpdf
  - R CMD check *tar.gz ## remove CRAN check --as-cran 

after_success:
  - git config --global user.name "Evan Biederstedt"
  - git config --global user.email evan.biederstedt@gmail.com
  - git config --global --list
  - Rscript - e 'rhub::check_on_solaris("evan.biederstedt@gmail.com")'